# Generated by Django 4.1.3 on 2022-11-10 11:42

from django.db import migrations, models
import django.db.models.deletion
import helpful.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("public", models.BooleanField(default=True, verbose_name="Public")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default=models.CharField(max_length=128, verbose_name="Name"),
                        max_length=256,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "header",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Header"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="Keywords"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "head_code",
                    models.TextField(blank=True, null=True, verbose_name="Head code"),
                ),
                (
                    "footer_code",
                    models.TextField(blank=True, null=True, verbose_name="Footer code"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=helpful.fields.upload_to,
                        verbose_name="Image",
                    ),
                ),
                (
                    "intro",
                    models.TextField(blank=True, null=True, verbose_name="Intro"),
                ),
                ("text", models.TextField(blank=True, null=True, verbose_name="Text")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", max_length=128, verbose_name="Slug"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        editable=False, max_length=2048, verbose_name="URL"
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Template"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=500, verbose_name="Position"),
                ),
                ("public", models.BooleanField(default=True, verbose_name="Public")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="content.page",
                        verbose_name="parent",
                    ),
                ),
                (
                    "sites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pages",
                        to="sites.site",
                        verbose_name="Sites",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ["position"],
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "header",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Header"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True, verbose_name="Text")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=helpful.fields.upload_to,
                        verbose_name="Image",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=500, verbose_name="Position"),
                ),
                ("public", models.BooleanField(default=True, verbose_name="Public")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="content.element",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Element",
                "verbose_name_plural": "Elements",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                ("slug", models.SlugField(verbose_name="Slug")),
                (
                    "header",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Header"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True, verbose_name="Text")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=helpful.fields.upload_to,
                        verbose_name="Image",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=500, verbose_name="Position"),
                ),
                ("public", models.BooleanField(default=True, verbose_name="Public")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="content.area",
                        verbose_name="Area",
                    ),
                ),
                (
                    "pages",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blocks",
                        to="content.page",
                        verbose_name="Pages",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="content.block",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block",
                "verbose_name_plural": "Blocks",
                "ordering": ["position", "created_at"],
            },
        ),
    ]
