# Generated by Django 4.1.3 on 2022-11-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="per_page",
            field=models.IntegerField(default=10, verbose_name="Items per page"),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Title"
            ),
        ),
    ]
