# Generated by Django 3.2.12 on 2022-04-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=128, unique=True, verbose_name='Webserverebene'),
        ),
    ]
