# Generated by Django 4.1.3 on 2022-11-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_page_per_page_alter_page_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID",),),
                ("title", models.CharField(max_length=256, verbose_name="Title")),
                ("url", models.CharField(max_length=2048, verbose_name="URL or URL RegEx"),),
                ("regex", models.BooleanField(default=False, verbose_name="RegEx")),
                ("public", models.BooleanField(default=True, verbose_name="Public")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at"),),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at"),),
            ],
            options={"verbose_name": "URL", "verbose_name_plural": "URLs", "ordering": ["-created_at"],},
        ),
        migrations.AddField(
            model_name="element",
            name="block",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="content.block", verbose_name="Block",
            ),
            preserve_default=False,
        ),
    ]
